### PR TITLE
changed selectors for video selection

### PR DESCRIPTION
**Pull request by Irantwomiles**
I updated the app.js file to be able to find the videos on the lessons page after they updated their site.

### CODE REVIEW

**Comment by theIYD** [comment]
Hey, thanks for the pull request @Irantwomiles 

Can you pull the latest changes and check if it's working ? 
A previous pull was also made related to the new UI fix and was merged

**Comment by Irantwomiles** [comment]
Seems to be working correctly, though I got this error 

`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Users\MyName\Desktop\Projects\coursehunt\start'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

when running `node start` , but it worked fine when I ran it using `node build/start.js` .

**Comment by theIYD** [comment]
The file `start.js` doesn't exist in the root directory, it exists in the `build` folder. 

Also, since it works, merging this pull request will be creating conflicts and also it's redundant as of now. I thank you for your contribution.

**Comment by theIYD** [comment]
@Irantwomiles Check out #23

**Pull request closed without merging**
